### ISSUE TITLE
Spectoken definition & implementation

### ISSUE THREAD

**Issue by bsantosALB** [5GZORRO/smart-contract-lifecycle-manager#17]
Provide a definition for spectokens, including their properties (token fungibility, etc.), workflows, etc.
Understanding on how spectokens are validated against spectrum certificates is needed.
Definition is required on how spectrum offer validation mechanisms works against spectrum certificates and spectokens. This validation is performed before the spectrum offer is registered in the Marketplace.

**Comment by Mike-no** [comment]
done
